language: python
python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10
    - 3.11

install:
    - pip install -r requirements/dev.txt
    - pip install coveralls

script:
    - make test

after_success:
    - coveralls
