language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

install:
    - pip install -r requirements/dev.txt
    - pip install coveralls

script:
    - py.test tests -v --cov=dicomsorter

after_success:
    - coveralls
